service: getting-started
frameworkVersion: "3"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  fibonacci:
    handler: handler.fibonacci
    events:
      - http:
          method: get
          path: fibonacci
