service: serverless

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

functions:
  hello:
    handler: handler.helloName
    events:
      - http:
          method: get
          path: hello
  fibonacci:
    handler: handler.fibonacchi
    events:
      - http:
          method: get
          path: fibonacci