service: serverless-api

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello