service: serverless
frameworkVersion: "3"

plugins:
  - serverless-webpack

package:
  patterns:
    - "!*.ts"
    - "!.eslintrc.cjs"
    - "handler.js"
    - "errorHandler.js"
    - "reqParamValidate.js"
    - "node_modules/@middy"
    - "node_modules/joi"
    - "node_modules/@hapi"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: handler.helloName
    events:
      - http:
          method: get
          path: hello
  fibonacci:
    handler: handler.fibonacchi
    events:
      - http:
          method: get
          path: fibonacci
