type Employee = {
  address: string;
  birth_date: Date;
  city: string;
  country: string;
  employee_id: number;
  extension: string;
  full_name: string;
  hire_date: Date;
  home_phone: number;
  notes: string;
  postal_code: number;
  report_address: string;
  report_birth_date: Date;
  report_city: string;
  report_country: string;
  report_employee_id: number;
  report_extension: string;
  report_full_name: string;
  report_hire_date: Date;
  report_home_phone: number;
  report_notes: string;
  report_postal_code: number;
  report_title: string;
  report_title_of_courtesy: string;
  title: string;
  title_of_courtesy: string;
};

export default Employee;
