CREATE TABLE IF NOT EXISTS "cities" (
	"city_slug" varchar(40),
	"city_name" varchar(50),
	"state" varchar(20),
	"meta_title" varchar(100),
	"meta_description" varchar(256),
	"h1" varchar(256),
	"h2" varchar(256),
	"sub_heading_text" varchar(256),
	"tick_1" varchar(256),
	"tick_2" varchar(256),
	"tick_3" varchar(256),
	"about_bookphysio" text
);

CREATE TABLE IF NOT EXISTS "clinics" (
	"full_name" varchar(60) NOT NULL,
	"registration_link" varchar(256) NOT NULL,
	"pms" varchar(20),
	"meta_title" varchar(100),
	"meta_description" varchar(256),
	"slug" varchar(100),
	"website" varchar(80) NOT NULL,
	"clinic_name" varchar,
	"display_on_web" boolean,
	"link_to_clinic_suburb_page" varchar,
	"full_address" varchar(256) NOT NULL,
	"city" varchar(50) NOT NULL,
	"suburb" varchar(50) NOT NULL,
	"state" varchar(20) NOT NULL,
	"postcode" varchar(10) NOT NULL,
	"email" varchar(50),
	"phone" varchar(30) NOT NULL,
	"nearby1_txt" varchar(40),
	"nearby1_link" varchar(40),
	"nearby2_txt" varchar(40),
	"nearby2_link" varchar(40),
	"nearby3_txt" varchar(40),
	"nearby3_link" varchar(40),
	"nearby4_txt" varchar(40),
	"nearby4_link" varchar(40),
	"about_clinic" text NOT NULL,
	"latitude" serial NOT NULL,
	"longitude" serial NOT NULL
);

CREATE TABLE IF NOT EXISTS "suburbs" (
	"suburb_id" serial PRIMARY KEY NOT NULL,
	"suburb_slug" varchar(50),
	"suburb_name" varchar(50),
	"city" varchar(50),
	"state" varchar(20),
	"postcode" integer,
	"meta_title" varchar(100),
	"meta_description" varchar(256),
	"h1" varchar(256),
	"h2" varchar(256),
	"about_bookphysio" text,
	"nearby1_link" varchar(40),
	"nearby1_txt" varchar(40),
	"nearby1_state" varchar(40),
	"nearby1_postcode" integer,
	"nearby2_link" varchar(40),
	"nearby2_txt" varchar(40),
	"nearby2_state" varchar(40),
	"nearby2_postcode" integer,
	"nearby3_link" varchar(40),
	"nearby3_txt" varchar(40),
	"nearby3_state" varchar(40),
	"nearby3_postcode" integer,
	"nearby4_link" varchar(40),
	"nearby4_txt" varchar(40),
	"nearby4_state" varchar(40),
	"nearby4_postcode" integer
);
