service: redistribution

plugins: 
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

  iam:
    role:
      name: redistributionRole
      statements:
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
            - "sqs:ReceiveMessage"
            - "sqs:DeleteMessage"
            - "sqs:GetQueueUrl"
          Resource: "arn:aws:sqs:${self:provider.region}:*:MyQueue"

functions:
  sender:
    handler: src/lambda/sender.handler
    events:
      - http:
          path: api/v1/redistribution
          method: post
  receiver: 
    handler: src/lambda/receiver.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn  
          batchSize: 10

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"
# RDS MySql
    # MySqlDB:
    #   Type: AWS::RDS::DBInstance
    #   Properties:
    #     MasterUsername: 
    #     MasterUserPassword: 
    #     DBInstanceClass: db.t2.micro
    #     Engine: mysql
    #     AllocatedStorage: 20
    
